---
name: DynamicFT
api: 4.0.0
version: 1.0
main: MCA7\DynamicFT\Main
author: OguzhanUmutlu , MCA7
description: Customizable floating text plugin for PocketMine-MP
commands:
  dynamicft:
    description: "Manage floating texts"
    permission: dynamicft.cmd
    aliases:
    - dft
permissions:
  dynamicft.cmd:
    description: "Manage floating texts"
    default: op
...
